site_name: Advanced ADB Manual
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji
  - admonition
  - footnotes
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Device Operations: sections/device-operations.md
  - Security: sections/security.md
  - Debugging: sections/debugging.md
  - Tools: sections/tools.md
  - Recovery: sections/recovery.md
